name: release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Release
        run: dotnet nuget push nupkgs/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --timeout 15
